blueprint:
  name: Automation 3 - Octopus 6 Hours Limit
  author: TechGuides
  source_url: https://github.com/MagicalTrev89/ha-blueprints-automations/blob/master/foxess-hypervolt/automation3-octopus6hours.yaml
  description: | 
    ## Stop Charging Reasons
    This automation will stop charging your EV when any of the following conditions are met:
    1. The charge time is about to exceed 5 Hours 55 mins, Will attempt to stop charging 5 minutes before the limit is reached.
    2. The charge time has exceeded 6 Hours. Notification will be sent if enabled.
  domain: automation
  homeassistant:
    min_version: 2025.8.3
  input:
    octopus_charge_time:
      name: Octopus Charge Time Sensor
      description: Custom Sensor that tracks the charge time in a 24 hour period based on the Hypervolt charge time
      selector:
        entity:
          filter:
            domain: sensor
    hypervolt_charging_entity:
      name: Hypervolt Charging Entity
      description: Hypervolt Entity that shows if the EV is currently charging
      selector:
        entity:
          filter:
            domain: switch
            integration: hypervolt_charger
    notification_device:
      name: Notification Device
      description: The mobile_app device to send notifications to, i.e notify.mobile_app_my_iphone, unfortuently, its not possible to provide a workable dropdown, you must get the name from your app
      selector:
        text:
    notification_event:
      name: Notification Event
      description: This sends a notification event to home-assistant which can used by other automations i.e blueprint-notification
      default: blueprint-notification
      selector:
        text:
    notification_enabled:
      name: Do you want to enable notifications?
      description: Enable or disable sending notifications
      default: true
      selector:
        boolean:
variables:
  notification_enabled: !input notification_enabled
triggers:
  - trigger: numeric_state
    id: daily_ev_charge_time
    entity_id: !input octopus_charge_time
    above: 1.917
  - trigger: state
    id: hypervolt_charging
    entity_id: !input hypervolt_charging_entity
    to: "on"
conditions:
  - condition: state
    entity_id: !input hypervolt_charging_entity
    state: 'on'
  - condition: numeric_state
    entity_id: !input octopus_charge_time
    above: 1.917
actions:
  - action: switch.turn_off
    target:
      entity_id: !input hypervolt_charging_entity
  - alias: Notification
    choose:
      - alias: Notify if enabled
        conditions:                
          - condition: template
            alias: Are Notifications Enabled? 
            value_template: >- 
              {{ notification_enabled }}
        sequence:
          - service: !input notification_device
            data:
              title: Car Charging Stopped
              message: "Charge time has exceeded 5 hours, Charging Stopped"         
  - event: !input notification_event
    event_data:
      title: Car Charging Stopped
      message: "Charge time has exceeded 5 hours, Charging Stopped"