blueprint:
  name: Automation 2 - Stop Charging
  author: TechGuides
  source_url: https://github.com/MagicalTrev89/ha-blueprints-automations/blob/master/foxess-hypervolt/automation2-stopcharging.yaml
  description: | 
    ## Stop Charging Reasons
    This will stop charging for a bunch of reasons:
    - If Free Electricity Period ends, Car is not charging and not in a cheap electricity period
    - TBC, Hypervolt not charging
    - TBC, End of off peak electricity period
    -- from legacy automation 2 - stop charging only if the hypervolt is not
     - Off Peak = off, time is after 11:30pm but before 05:30am, stop charging
    -- from legacy automation 2a - stop charging if car is connected but not charging
     - Time = 05:29:55, plugged in, current is < 0, workmode is force charge, stop charge
    -- from legacy automation 4 - stop during day
     - Off Peak = off OR hypervolt charging = Off, After 05:30 > before 11:30, stop charging
  domain: automation
  homeassistant:
    min_version: 2025.8.3
  input:
    octopus_free_electricity:
      name: Octopus Energy Free Electricity Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            integration: octopus_energy
    octopus_off_peak:
      name: Octopus Energy Off Peak Electricity Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            integration: octopus_energy
    foxess_modbus_discharge_current:
      name: FoxESS Inverter Discharge Current
      selector:
        entity:
          filter:
            domain: number
            integration: foxess_modbus
    foxess_modbus_work_mode:
      name: FoxESS Inverter Work Mode
      selector:
        entity:
          filter:
            domain: select
            integration: foxess_modbus
    hypervolt_charger_current:
      name: Hypervolt Charger Current
      selector:
        entity:
          filter:
            domain: sensor
            integration: hypervolt_charger
triggers:
  - trigger: state
    entity_id: !input octopus_free_electricity
    from: "on"
    to: "off"
  - trigger: state
    entity_id: !input octopus_off_peak
    from: "on"
    to: "off"
    enabled: false
    

action:
  # 1) 
  - choose:
      - conditions:
          - condition: state
            entity_id: !input octopus_free_electricity
            state: "off"
          - condition: numeric_state
            entity_id: !input hypervolt_charger_current
            below: 1
          - condition: state
            entity_id: !input octopus_off_peak
            state: "off"
        sequence:
          - action: number.set_value
            alias: Set Discharge Current to 40
            target:
              entity_id: !input foxess_modbus_discharge_current
            metadata: {}
            data:
              value: "40"
          - action: select.select_option
            alias: Set Work Mode to Self Use
            metadata: {}
            data:
              option: Self Use
            target:
              entity_id: !input foxess_modbus_work_mode
