blueprint:
  name: Automation 2 - Stop Charging
  author: TechGuides
  source_url: https://github.com/MagicalTrev89/ha-blueprints-automations/blob/master/foxess-hypervolt/automation2-stopcharging.yaml
  description: | 
    ## Stop Charging Reasons
    This will stop charging for a bunch of reasons:
    * If Free Electricity Period ends, Car is not charging and not in a cheap electricity period
    * TBC, Hypervolt not charging
    * TBC, End of off peak electricity period
      * from legacy automation 2 - stop charging only if the hypervolt is not
        * Off Peak = off, time is after 11:30pm but before 05:30am, stop charging
      * from legacy automation 2a - stop charging if car is connected but not charging
        * Time = 05:29:55, plugged in, current is < 0, workmode is force charge, stop charge
      * from legacy automation 4 - stop during day
        * Off Peak = off OR hypervolt charging = Off, After 05:30 > before 11:30, stop charging
  domain: automation
  homeassistant:
    min_version: 2025.8.3
  input:
    octopus_free_electricity:
      name: Octopus Energy Free Electricity Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            integration: octopus_energy
    octopus_off_peak:
      name: Octopus Energy Off Peak Electricity Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            integration: octopus_energy
    foxess_modbus_discharge_current:
      name: FoxESS Inverter Discharge Current
      selector:
        entity:
          filter:
            domain: number
            integration: foxess_modbus
    foxess_modbus_work_mode:
      name: FoxESS Inverter Work Mode
      selector:
        entity:
          filter:
            domain: select
            integration: foxess_modbus
    hypervolt_ev_power:
      name: Hypervolt EV Power
      selector:
        entity:
          filter:
            domain: sensor
            integration: hypervolt_charger
triggers:
  - trigger: state
    id: Free Electricity
    entity_id: !input octopus_free_electricity
    from: "on"
    to: "off"
  - trigger: time
    id: Time 05:29:55
    # This is needed because sometimes the car could be plugged in and not charging, but octopus may still have a cheap energy period active
    # do not want to risk using cheap electricity because the car wont charge, therefore octopus can take it away.
    at: "05:29:55"
    enabled: true
  - trigger: numeric_state
    id: EV Power 0
    entity_id: !input hypervolt_ev_power
    below: 1
    enabled: true
action:
  # 1) 
  - choose:
      - conditions:
      # This condition triggers usually only if the battery protection has kicked in but the charging never starts, this sometimes happens
      # for some reason, maybe its that octopus changes its mind
      # not tested but this condition will likely be good for a charge boost
          - condition: trigger
            id:
              - EV Power 0
          - condition: time
            after: "05:30:00"
            before: "23:30:00"
            weekday:
              - sun
              - sat
              - fri
              - wed
              - thu
              - tue
              - mon
          - condition: state
            alias: Inverter is in Self use mode
            entity_id: !input foxess_modbus_work_mode
            state:
              - Self Use
        sequence:
          - action: number.set_value
            alias: Set Discharge Current to 40
            target:
              entity_id: !input foxess_modbus_discharge_current
            metadata: {}
            data:
              value: "40"
        alias: Car Stops Charging, During Day, Inverter not already charging
      - conditions:
          - condition: trigger
            id:
              - EV Power 0
          - condition: time
            after: "05:30:00"
            before: "23:30:00"
            weekday:
              - sun
              - sat
              - fri
              - wed
              - thu
              - tue
              - mon
          - condition: state
            alias: Inverter is in Charging Mode
            entity_id: !input foxess_modbus_work_mode
            state:
              - Force Charge
        sequence:
          - action: number.set_value
            alias: Set Discharge Current to 40
            target:
              entity_id: !input foxess_modbus_discharge_current
            metadata: {}
            data:
              value: "40"
          - action: select.select_option
            alias: Set Work Mode to Self Use
            metadata: {}
            data:
              option: Self Use
            target:
              entity_id: !input foxess_modbus_work_mode
        alias: Car Stops Charging, During Day, Stop Charging
      - conditions:
          - condition: trigger
            id:
              - Time 05:29:55
          - condition: numeric_state
            entity_id: !input hypervolt_ev_power
            below: 1
          - condition: state
            alias: Inverter is in Charging Mode
            entity_id: !input foxess_modbus_work_mode
            state:
              - Force Charge
        sequence: 
          - action: number.set_value
            alias: Set Discharge Current to 40
            target:
              entity_id: !input foxess_modbus_discharge_current
            metadata: {}
            data:
              value: "40"
          - action: select.select_option
            alias: Set Work Mode to Self Use
            metadata: {}
            data:
              option: Self Use
            target:
              entity_id: !input foxess_modbus_work_mode
        alias: When its end of night, car isnt charging, stop charge
      - conditions:
          - condition: trigger
            id:
              - Free Electricity
          - condition: numeric_state
            entity_id: !input hypervolt_ev_power
            below: 1
          - condition: state
            # This condition is needed as sometimes the free electricity period can end but off peak can be active like at 11:30pm
            entity_id: !input octopus_off_peak
            state: "off"
        sequence:
          - action: number.set_value
            alias: Set Discharge Current to 40
            target:
              entity_id: !input foxess_modbus_discharge_current
            metadata: {}
            data:
              value: "40"
          - action: select.select_option
            alias: Set Work Mode to Self Use
            metadata: {}
            data:
              option: Self Use
            target:
              entity_id: !input foxess_modbus_work_mode
        alias: Free Electricity End
